FROM golang:alpine3.18 AS build
RUN apk add build-base git
WORKDIR /src
COPY . .
RUN make build_linux

FROM alpine:latest
RUN apk add --no-cache ca-certificates && \
    update-ca-certificates
COPY --from=build /src/_output/linux/narr /usr/local/bin/narr
EXPOSE 7049
ENTRYPOINT ["/usr/local/bin/narr"]
CMD ["-addr", "0.0.0.0:7049", "-db", "/data/narr.db"]
